"""initial schema

Revision ID: 50d5b46784ac
Revises: 
Create Date: 2026-05-22 11:29:07.382587
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50d5b46784ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('matrix_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('contracts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['matrix_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrix_versions_tenant_id'), 'matrix_versions', ['tenant_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_config', sa.JSON(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_tenant_id'), 'runs', ['tenant_id'], unique=False)
    op.create_table('sgt_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('sgt_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sgt_id', name='uq_sgt_tenant_id')
    )
    op.create_table('threat_lookups',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_lookups_tenant_id'), 'threat_lookups', ['tenant_id'], unique=False)
    op.create_index('ix_threat_target_provider', 'threat_lookups', ['target', 'provider', 'fetched_at'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('src_sgt', sa.Integer(), nullable=False),
    sa.Column('dst_sgt', sa.Integer(), nullable=False),
    sa.Column('src_sgt_name', sa.String(length=128), nullable=False),
    sa.Column('dst_sgt_name', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'src_sgt', 'dst_sgt', name='uq_contract_run_pair')
    )
    op.create_index(op.f('ix_contracts_run_id'), 'contracts', ['run_id'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.create_table('flow_classifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('sgt', sa.Integer(), nullable=False),
    sa.Column('dgt', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('src_port', sa.String(length=16), nullable=False),
    sa.Column('dst_port', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('total_hits', sa.Integer(), nullable=False),
    sa.Column('classified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sgt', 'dgt', 'protocol', 'src_port', 'dst_port', name='uq_classification_run_flow')
    )
    op.create_index('ix_classifications_flow_cache', 'flow_classifications', ['tenant_id', 'sgt', 'dgt', 'protocol', 'src_port', 'dst_port', 'classified_at'], unique=False)
    op.create_index(op.f('ix_flow_classifications_run_id'), 'flow_classifications', ['run_id'], unique=False)
    op.create_index(op.f('ix_flow_classifications_tenant_id'), 'flow_classifications', ['tenant_id'], unique=False)
    op.create_table('flow_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('ingestion_ts', sa.DateTime(), nullable=False),
    sa.Column('sgt', sa.Integer(), nullable=False),
    sa.Column('dgt', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('src_port', sa.String(length=16), nullable=False),
    sa.Column('dst_port', sa.String(length=16), nullable=False),
    sa.Column('src_ip', sa.String(length=64), nullable=True),
    sa.Column('dst_ip', sa.String(length=64), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('sgacl_name', sa.String(length=128), nullable=True),
    sa.Column('observed_action', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_events_run_id'), 'flow_events', ['run_id'], unique=False)
    op.create_index(op.f('ix_flow_events_tenant_id'), 'flow_events', ['tenant_id'], unique=False)
    op.create_index('ix_flow_events_tenant_sgt_dgt', 'flow_events', ['tenant_id', 'sgt', 'dgt'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('trigger_ref', sa.String(length=128), nullable=True),
    sa.Column('src_sgt', sa.Integer(), nullable=False),
    sa.Column('dst_sgt', sa.Integer(), nullable=False),
    sa.Column('proposed_aces', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('threat_context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decision_channel', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_proposal_idem')
    )
    op.create_index('ix_proposals_pending_pair', 'proposals', ['tenant_id', 'src_sgt', 'dst_sgt', 'status'], unique=False)
    op.create_index(op.f('ix_proposals_tenant_id'), 'proposals', ['tenant_id'], unique=False)
    op.create_table('contract_aces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('src_port', sa.String(length=16), nullable=False),
    sa.Column('dst_port', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('source_category', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_aces_contract_id'), 'contract_aces', ['contract_id'], unique=False)
    op.create_table('proposal_audit',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_audit_proposal_id'), 'proposal_audit', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_audit_proposal_id'), table_name='proposal_audit')
    op.drop_table('proposal_audit')
    op.drop_index(op.f('ix_contract_aces_contract_id'), table_name='contract_aces')
    op.drop_table('contract_aces')
    op.drop_index(op.f('ix_proposals_tenant_id'), table_name='proposals')
    op.drop_index('ix_proposals_pending_pair', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('ix_flow_events_tenant_sgt_dgt', table_name='flow_events')
    op.drop_index(op.f('ix_flow_events_tenant_id'), table_name='flow_events')
    op.drop_index(op.f('ix_flow_events_run_id'), table_name='flow_events')
    op.drop_table('flow_events')
    op.drop_index(op.f('ix_flow_classifications_tenant_id'), table_name='flow_classifications')
    op.drop_index(op.f('ix_flow_classifications_run_id'), table_name='flow_classifications')
    op.drop_index('ix_classifications_flow_cache', table_name='flow_classifications')
    op.drop_table('flow_classifications')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_run_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_threat_target_provider', table_name='threat_lookups')
    op.drop_index(op.f('ix_threat_lookups_tenant_id'), table_name='threat_lookups')
    op.drop_table('threat_lookups')
    op.drop_table('sgt_entries')
    op.drop_index(op.f('ix_runs_tenant_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_matrix_versions_tenant_id'), table_name='matrix_versions')
    op.drop_table('matrix_versions')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
